apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drizzler.fullname" . }}-config
  labels:
    {{- include "drizzler.labels" . | nindent 4 }}
data:
  HTTP_REQUEST_TIMEOUT_S: {{ .Values.config.httpRequestTimeoutS | quote }}
  LLM_MODEL: {{ .Values.config.llmModel | quote }}
  {{- if .Values.config.llmHost }}
  LLM_HOST: {{ .Values.config.llmHost | quote }}
  {{- end }}
  {{- if .Values.config.ytdlpCookiesPath }}
  YTDLP_COOKIES_PATH: {{ .Values.config.ytdlpCookiesPath | quote }}
  {{- end }}
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"
