apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drizzler.fullname" . }}-secret
  labels:
    {{- include "drizzler.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.googleApiKey }}
  GOOGLE_API_KEY: {{ .Values.secrets.googleApiKey | b64enc | quote }}
  {{- end }}
